spring:
  profiles:
    active: local

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
    database: mysql

  thymeleaf:
    enabled: true
    cache: false
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

  messages:
    basename: messages/exception
    encoding: UTF-8
    fallbackToSystemLocale: false
    alwaysUseMessageFormat: true

jwt:
  secret-key: 71b2def514eb60cc80e5b701aa5c6de66c33e9699e9a7f615a6a9998ae190c3db5a985081c8a150cf1d9b7fa9f32aa9bfcb568d9eda911c88274ead183ddb15e
  expiration-time: 86400000
  cookie-name: fintrack_token

slack:
  webhook:
    url: https://hooks.slack.com/services/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