spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://fintrack-db.cn20uwoke2ya.ap-northeast-2.rds.amazonaws.com:3306/fintrack
    username: sun
    password: sun0216!

oauth2:
  kakao:
    client-id: 5e7ce3d83dc7c861fe2ea3a1daa2dacf
    client-secret: QfRo0xCyPyK7WNx43A3YePurJH7DvnNz
    redirect-uri: https://fintrack.site/auth/kakao
    scope: profile_nickname,account_email
    authorize-uri: https://kauth.kakao.com/oauth/authorize
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
    authorization-prefix: 'Bearer '