/*
 * This file is generated by jOOQ.
 */
package sun;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import sun.tables.Asset;
import sun.tables.Member;
import sun.tables.Payment;
import sun.tables.PaymentCategory;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Fintrack extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>fintrack</code>
     */
    public static final Fintrack FINTRACK = new Fintrack();

    /**
     * 자산 테이블
     */
    public final Asset ASSET = Asset.ASSET;

    /**
     * The table <code>fintrack.MEMBER</code>.
     */
    public final Member MEMBER = Member.MEMBER;

    /**
     * The table <code>fintrack.PAYMENT</code>.
     */
    public final Payment PAYMENT = Payment.PAYMENT;

    /**
     * The table <code>fintrack.PAYMENT_CATEGORY</code>.
     */
    public final PaymentCategory PAYMENT_CATEGORY = PaymentCategory.PAYMENT_CATEGORY;

    /**
     * No further instances allowed
     */
    private Fintrack() {
        super("fintrack", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Asset.ASSET,
            Member.MEMBER,
            Payment.PAYMENT,
            PaymentCategory.PAYMENT_CATEGORY
        );
    }
}
