/*
 * This file is generated by jOOQ.
 */
package sun;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import sun.tables.Member;
import sun.tables.records.MemberRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in sun.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MemberRecord> MEMBER_PKEY = Internal.createUniqueKey(Member.MEMBER, DSL.name("member_pkey"), new TableField[] { Member.MEMBER.MB_SEQ }, true);
}
