/*
 * This file is generated by jOOQ.
 */
package sun;


import sun.tables.Asset;
import sun.tables.Member;
import sun.tables.Payment;
import sun.tables.PaymentCategory;


/**
 * Convenience access to all tables in fintrack.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * 자산 테이블
     */
    public static final Asset ASSET = Asset.ASSET;

    /**
     * The table <code>fintrack.MEMBER</code>.
     */
    public static final Member MEMBER = Member.MEMBER;

    /**
     * The table <code>fintrack.PAYMENT</code>.
     */
    public static final Payment PAYMENT = Payment.PAYMENT;

    /**
     * The table <code>fintrack.PAYMENT_CATEGORY</code>.
     */
    public static final PaymentCategory PAYMENT_CATEGORY = PaymentCategory.PAYMENT_CATEGORY;
}
