/*
 * This file is generated by jOOQ.
 */
package sun;


import sun.tables.Asset;
import sun.tables.Category;
import sun.tables.Member;
import sun.tables.Trade;


/**
 * Convenience access to all tables in fintrack.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * 자산 테이블
     */
    public static final Asset ASSET = Asset.ASSET;

    /**
     * 카테고리 테이블
     */
    public static final Category CATEGORY = Category.CATEGORY;

    /**
     * The table <code>fintrack.MEMBER</code>.
     */
    public static final Member MEMBER = Member.MEMBER;

    /**
     * 거래 내역 테이블
     */
    public static final Trade TRADE = Trade.TRADE;
}
