/*
 * This file is generated by jOOQ.
 */
package sun.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 카테고리 테이블
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Category implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long ctgSeq;
    private final String ctgNm;
    private final Integer ctgOrd;
    private final String ctgTyp;
    private final Long mbSeq;
    private final LocalDateTime creDt;
    private final LocalDateTime updDt;

    public Category(Category value) {
        this.ctgSeq = value.ctgSeq;
        this.ctgNm = value.ctgNm;
        this.ctgOrd = value.ctgOrd;
        this.ctgTyp = value.ctgTyp;
        this.mbSeq = value.mbSeq;
        this.creDt = value.creDt;
        this.updDt = value.updDt;
    }

    public Category(
        Long ctgSeq,
        String ctgNm,
        Integer ctgOrd,
        String ctgTyp,
        Long mbSeq,
        LocalDateTime creDt,
        LocalDateTime updDt
    ) {
        this.ctgSeq = ctgSeq;
        this.ctgNm = ctgNm;
        this.ctgOrd = ctgOrd;
        this.ctgTyp = ctgTyp;
        this.mbSeq = mbSeq;
        this.creDt = creDt;
        this.updDt = updDt;
    }

    /**
     * Getter for <code>fintrack.CATEGORY.CTG_SEQ</code>. 카테고리 일련번호
     */
    public Long getCtgSeq() {
        return this.ctgSeq;
    }

    /**
     * Getter for <code>fintrack.CATEGORY.CTG_NM</code>. 카테고리명
     */
    public String getCtgNm() {
        return this.ctgNm;
    }

    /**
     * Getter for <code>fintrack.CATEGORY.CTG_ORD</code>. 카테고리 순서
     */
    public Integer getCtgOrd() {
        return this.ctgOrd;
    }

    /**
     * Getter for <code>fintrack.CATEGORY.CTG_TYP</code>. 카테고리 타입
     */
    public String getCtgTyp() {
        return this.ctgTyp;
    }

    /**
     * Getter for <code>fintrack.CATEGORY.MB_SEQ</code>. 회원 일련번호
     */
    public Long getMbSeq() {
        return this.mbSeq;
    }

    /**
     * Getter for <code>fintrack.CATEGORY.CRE_DT</code>. 등록일시
     */
    public LocalDateTime getCreDt() {
        return this.creDt;
    }

    /**
     * Getter for <code>fintrack.CATEGORY.UPD_DT</code>. 수정일시
     */
    public LocalDateTime getUpdDt() {
        return this.updDt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Category other = (Category) obj;
        if (this.ctgSeq == null) {
            if (other.ctgSeq != null)
                return false;
        }
        else if (!this.ctgSeq.equals(other.ctgSeq))
            return false;
        if (this.ctgNm == null) {
            if (other.ctgNm != null)
                return false;
        }
        else if (!this.ctgNm.equals(other.ctgNm))
            return false;
        if (this.ctgOrd == null) {
            if (other.ctgOrd != null)
                return false;
        }
        else if (!this.ctgOrd.equals(other.ctgOrd))
            return false;
        if (this.ctgTyp == null) {
            if (other.ctgTyp != null)
                return false;
        }
        else if (!this.ctgTyp.equals(other.ctgTyp))
            return false;
        if (this.mbSeq == null) {
            if (other.mbSeq != null)
                return false;
        }
        else if (!this.mbSeq.equals(other.mbSeq))
            return false;
        if (this.creDt == null) {
            if (other.creDt != null)
                return false;
        }
        else if (!this.creDt.equals(other.creDt))
            return false;
        if (this.updDt == null) {
            if (other.updDt != null)
                return false;
        }
        else if (!this.updDt.equals(other.updDt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.ctgSeq == null) ? 0 : this.ctgSeq.hashCode());
        result = prime * result + ((this.ctgNm == null) ? 0 : this.ctgNm.hashCode());
        result = prime * result + ((this.ctgOrd == null) ? 0 : this.ctgOrd.hashCode());
        result = prime * result + ((this.ctgTyp == null) ? 0 : this.ctgTyp.hashCode());
        result = prime * result + ((this.mbSeq == null) ? 0 : this.mbSeq.hashCode());
        result = prime * result + ((this.creDt == null) ? 0 : this.creDt.hashCode());
        result = prime * result + ((this.updDt == null) ? 0 : this.updDt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Category (");

        sb.append(ctgSeq);
        sb.append(", ").append(ctgNm);
        sb.append(", ").append(ctgOrd);
        sb.append(", ").append(ctgTyp);
        sb.append(", ").append(mbSeq);
        sb.append(", ").append(creDt);
        sb.append(", ").append(updDt);

        sb.append(")");
        return sb.toString();
    }
}
