/*
 * This file is generated by jOOQ.
 */
package sun.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 수입 테이블
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Income implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long icSeq;
    private final Long mbSeq;
    private final String icCtt;
    private final Long icPrc;
    private final LocalDateTime icDt;
    private final Long asSeq;
    private final Long ctgId;
    private final LocalDateTime creDt;
    private final LocalDateTime updDt;

    public Income(Income value) {
        this.icSeq = value.icSeq;
        this.mbSeq = value.mbSeq;
        this.icCtt = value.icCtt;
        this.icPrc = value.icPrc;
        this.icDt = value.icDt;
        this.asSeq = value.asSeq;
        this.ctgId = value.ctgId;
        this.creDt = value.creDt;
        this.updDt = value.updDt;
    }

    public Income(
        Long icSeq,
        Long mbSeq,
        String icCtt,
        Long icPrc,
        LocalDateTime icDt,
        Long asSeq,
        Long ctgId,
        LocalDateTime creDt,
        LocalDateTime updDt
    ) {
        this.icSeq = icSeq;
        this.mbSeq = mbSeq;
        this.icCtt = icCtt;
        this.icPrc = icPrc;
        this.icDt = icDt;
        this.asSeq = asSeq;
        this.ctgId = ctgId;
        this.creDt = creDt;
        this.updDt = updDt;
    }

    /**
     * Getter for <code>fintrack.INCOME.IC_SEQ</code>. 수입 일련번호
     */
    public Long getIcSeq() {
        return this.icSeq;
    }

    /**
     * Getter for <code>fintrack.INCOME.MB_SEQ</code>. 회원 일련번호
     */
    public Long getMbSeq() {
        return this.mbSeq;
    }

    /**
     * Getter for <code>fintrack.INCOME.IC_CTT</code>. 수입 내용
     */
    public String getIcCtt() {
        return this.icCtt;
    }

    /**
     * Getter for <code>fintrack.INCOME.IC_PRC</code>. 수입 금액
     */
    public Long getIcPrc() {
        return this.icPrc;
    }

    /**
     * Getter for <code>fintrack.INCOME.IC_DT</code>. 수입일시
     */
    public LocalDateTime getIcDt() {
        return this.icDt;
    }

    /**
     * Getter for <code>fintrack.INCOME.AS_SEQ</code>. 자산 일련번호
     */
    public Long getAsSeq() {
        return this.asSeq;
    }

    /**
     * Getter for <code>fintrack.INCOME.CTG_ID</code>. 카테고리 아이디
     */
    public Long getCtgId() {
        return this.ctgId;
    }

    /**
     * Getter for <code>fintrack.INCOME.CRE_DT</code>. 등록일시
     */
    public LocalDateTime getCreDt() {
        return this.creDt;
    }

    /**
     * Getter for <code>fintrack.INCOME.UPD_DT</code>. 수정일시
     */
    public LocalDateTime getUpdDt() {
        return this.updDt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Income other = (Income) obj;
        if (this.icSeq == null) {
            if (other.icSeq != null)
                return false;
        }
        else if (!this.icSeq.equals(other.icSeq))
            return false;
        if (this.mbSeq == null) {
            if (other.mbSeq != null)
                return false;
        }
        else if (!this.mbSeq.equals(other.mbSeq))
            return false;
        if (this.icCtt == null) {
            if (other.icCtt != null)
                return false;
        }
        else if (!this.icCtt.equals(other.icCtt))
            return false;
        if (this.icPrc == null) {
            if (other.icPrc != null)
                return false;
        }
        else if (!this.icPrc.equals(other.icPrc))
            return false;
        if (this.icDt == null) {
            if (other.icDt != null)
                return false;
        }
        else if (!this.icDt.equals(other.icDt))
            return false;
        if (this.asSeq == null) {
            if (other.asSeq != null)
                return false;
        }
        else if (!this.asSeq.equals(other.asSeq))
            return false;
        if (this.ctgId == null) {
            if (other.ctgId != null)
                return false;
        }
        else if (!this.ctgId.equals(other.ctgId))
            return false;
        if (this.creDt == null) {
            if (other.creDt != null)
                return false;
        }
        else if (!this.creDt.equals(other.creDt))
            return false;
        if (this.updDt == null) {
            if (other.updDt != null)
                return false;
        }
        else if (!this.updDt.equals(other.updDt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.icSeq == null) ? 0 : this.icSeq.hashCode());
        result = prime * result + ((this.mbSeq == null) ? 0 : this.mbSeq.hashCode());
        result = prime * result + ((this.icCtt == null) ? 0 : this.icCtt.hashCode());
        result = prime * result + ((this.icPrc == null) ? 0 : this.icPrc.hashCode());
        result = prime * result + ((this.icDt == null) ? 0 : this.icDt.hashCode());
        result = prime * result + ((this.asSeq == null) ? 0 : this.asSeq.hashCode());
        result = prime * result + ((this.ctgId == null) ? 0 : this.ctgId.hashCode());
        result = prime * result + ((this.creDt == null) ? 0 : this.creDt.hashCode());
        result = prime * result + ((this.updDt == null) ? 0 : this.updDt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Income (");

        sb.append(icSeq);
        sb.append(", ").append(mbSeq);
        sb.append(", ").append(icCtt);
        sb.append(", ").append(icPrc);
        sb.append(", ").append(icDt);
        sb.append(", ").append(asSeq);
        sb.append(", ").append(ctgId);
        sb.append(", ").append(creDt);
        sb.append(", ").append(updDt);

        sb.append(")");
        return sb.toString();
    }
}
