/*
 * This file is generated by jOOQ.
 */
package sun.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Member implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long mbSeq;
    private final String mbEmail;
    private final String mbNm;
    private final String mbRole;
    private final String mbValid;
    private final LocalDateTime creDt;
    private final LocalDateTime updDt;

    public Member(Member value) {
        this.mbSeq = value.mbSeq;
        this.mbEmail = value.mbEmail;
        this.mbNm = value.mbNm;
        this.mbRole = value.mbRole;
        this.mbValid = value.mbValid;
        this.creDt = value.creDt;
        this.updDt = value.updDt;
    }

    public Member(
        Long mbSeq,
        String mbEmail,
        String mbNm,
        String mbRole,
        String mbValid,
        LocalDateTime creDt,
        LocalDateTime updDt
    ) {
        this.mbSeq = mbSeq;
        this.mbEmail = mbEmail;
        this.mbNm = mbNm;
        this.mbRole = mbRole;
        this.mbValid = mbValid;
        this.creDt = creDt;
        this.updDt = updDt;
    }

    /**
     * Getter for <code>fintrack.MEMBER.MB_SEQ</code>. 회원 일련번호
     */
    public Long getMbSeq() {
        return this.mbSeq;
    }

    /**
     * Getter for <code>fintrack.MEMBER.MB_EMAIL</code>. 이메일
     */
    public String getMbEmail() {
        return this.mbEmail;
    }

    /**
     * Getter for <code>fintrack.MEMBER.MB_NM</code>. 닉네임
     */
    public String getMbNm() {
        return this.mbNm;
    }

    /**
     * Getter for <code>fintrack.MEMBER.MB_ROLE</code>. 권한
     */
    public String getMbRole() {
        return this.mbRole;
    }

    /**
     * Getter for <code>fintrack.MEMBER.MB_VALID</code>. 유효여부
     */
    public String getMbValid() {
        return this.mbValid;
    }

    /**
     * Getter for <code>fintrack.MEMBER.CRE_DT</code>. 등록일시
     */
    public LocalDateTime getCreDt() {
        return this.creDt;
    }

    /**
     * Getter for <code>fintrack.MEMBER.UPD_DT</code>. 수정일시
     */
    public LocalDateTime getUpdDt() {
        return this.updDt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Member other = (Member) obj;
        if (this.mbSeq == null) {
            if (other.mbSeq != null)
                return false;
        }
        else if (!this.mbSeq.equals(other.mbSeq))
            return false;
        if (this.mbEmail == null) {
            if (other.mbEmail != null)
                return false;
        }
        else if (!this.mbEmail.equals(other.mbEmail))
            return false;
        if (this.mbNm == null) {
            if (other.mbNm != null)
                return false;
        }
        else if (!this.mbNm.equals(other.mbNm))
            return false;
        if (this.mbRole == null) {
            if (other.mbRole != null)
                return false;
        }
        else if (!this.mbRole.equals(other.mbRole))
            return false;
        if (this.mbValid == null) {
            if (other.mbValid != null)
                return false;
        }
        else if (!this.mbValid.equals(other.mbValid))
            return false;
        if (this.creDt == null) {
            if (other.creDt != null)
                return false;
        }
        else if (!this.creDt.equals(other.creDt))
            return false;
        if (this.updDt == null) {
            if (other.updDt != null)
                return false;
        }
        else if (!this.updDt.equals(other.updDt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.mbSeq == null) ? 0 : this.mbSeq.hashCode());
        result = prime * result + ((this.mbEmail == null) ? 0 : this.mbEmail.hashCode());
        result = prime * result + ((this.mbNm == null) ? 0 : this.mbNm.hashCode());
        result = prime * result + ((this.mbRole == null) ? 0 : this.mbRole.hashCode());
        result = prime * result + ((this.mbValid == null) ? 0 : this.mbValid.hashCode());
        result = prime * result + ((this.creDt == null) ? 0 : this.creDt.hashCode());
        result = prime * result + ((this.updDt == null) ? 0 : this.updDt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Member (");

        sb.append(mbSeq);
        sb.append(", ").append(mbEmail);
        sb.append(", ").append(mbNm);
        sb.append(", ").append(mbRole);
        sb.append(", ").append(mbValid);
        sb.append(", ").append(creDt);
        sb.append(", ").append(updDt);

        sb.append(")");
        return sb.toString();
    }
}
