/*
 * This file is generated by jOOQ.
 */
package sun.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 거래 내역 테이블
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Trade implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long trdSeq;
    private final Long mbSeq;
    private final String trdCtt;
    private final Long trdPrc;
    private final LocalDateTime trdDt;
    private final String trdTyp;
    private final Long asSeq;
    private final Long ctgSeq;
    private final String trdImgPath;
    private final LocalDateTime creDt;
    private final LocalDateTime updDt;

    public Trade(Trade value) {
        this.trdSeq = value.trdSeq;
        this.mbSeq = value.mbSeq;
        this.trdCtt = value.trdCtt;
        this.trdPrc = value.trdPrc;
        this.trdDt = value.trdDt;
        this.trdTyp = value.trdTyp;
        this.asSeq = value.asSeq;
        this.ctgSeq = value.ctgSeq;
        this.trdImgPath = value.trdImgPath;
        this.creDt = value.creDt;
        this.updDt = value.updDt;
    }

    public Trade(
        Long trdSeq,
        Long mbSeq,
        String trdCtt,
        Long trdPrc,
        LocalDateTime trdDt,
        String trdTyp,
        Long asSeq,
        Long ctgSeq,
        String trdImgPath,
        LocalDateTime creDt,
        LocalDateTime updDt
    ) {
        this.trdSeq = trdSeq;
        this.mbSeq = mbSeq;
        this.trdCtt = trdCtt;
        this.trdPrc = trdPrc;
        this.trdDt = trdDt;
        this.trdTyp = trdTyp;
        this.asSeq = asSeq;
        this.ctgSeq = ctgSeq;
        this.trdImgPath = trdImgPath;
        this.creDt = creDt;
        this.updDt = updDt;
    }

    /**
     * Getter for <code>fintrack.TRADE.TRD_SEQ</code>. 거래 일련번호
     */
    public Long getTrdSeq() {
        return this.trdSeq;
    }

    /**
     * Getter for <code>fintrack.TRADE.MB_SEQ</code>. 회원 일련번호
     */
    public Long getMbSeq() {
        return this.mbSeq;
    }

    /**
     * Getter for <code>fintrack.TRADE.TRD_CTT</code>. 거래 내용
     */
    public String getTrdCtt() {
        return this.trdCtt;
    }

    /**
     * Getter for <code>fintrack.TRADE.TRD_PRC</code>. 거래 금액
     */
    public Long getTrdPrc() {
        return this.trdPrc;
    }

    /**
     * Getter for <code>fintrack.TRADE.TRD_DT</code>. 거래일시
     */
    public LocalDateTime getTrdDt() {
        return this.trdDt;
    }

    /**
     * Getter for <code>fintrack.TRADE.TRD_TYP</code>. 거래 타입
     */
    public String getTrdTyp() {
        return this.trdTyp;
    }

    /**
     * Getter for <code>fintrack.TRADE.AS_SEQ</code>. 자산 일련번호
     */
    public Long getAsSeq() {
        return this.asSeq;
    }

    /**
     * Getter for <code>fintrack.TRADE.CTG_SEQ</code>. 카테고리 일련번호
     */
    public Long getCtgSeq() {
        return this.ctgSeq;
    }

    /**
     * Getter for <code>fintrack.TRADE.TRD_IMG_PATH</code>. 이미지 경로
     */
    public String getTrdImgPath() {
        return this.trdImgPath;
    }

    /**
     * Getter for <code>fintrack.TRADE.CRE_DT</code>. 등록일시
     */
    public LocalDateTime getCreDt() {
        return this.creDt;
    }

    /**
     * Getter for <code>fintrack.TRADE.UPD_DT</code>. 수정일시
     */
    public LocalDateTime getUpdDt() {
        return this.updDt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Trade other = (Trade) obj;
        if (this.trdSeq == null) {
            if (other.trdSeq != null)
                return false;
        }
        else if (!this.trdSeq.equals(other.trdSeq))
            return false;
        if (this.mbSeq == null) {
            if (other.mbSeq != null)
                return false;
        }
        else if (!this.mbSeq.equals(other.mbSeq))
            return false;
        if (this.trdCtt == null) {
            if (other.trdCtt != null)
                return false;
        }
        else if (!this.trdCtt.equals(other.trdCtt))
            return false;
        if (this.trdPrc == null) {
            if (other.trdPrc != null)
                return false;
        }
        else if (!this.trdPrc.equals(other.trdPrc))
            return false;
        if (this.trdDt == null) {
            if (other.trdDt != null)
                return false;
        }
        else if (!this.trdDt.equals(other.trdDt))
            return false;
        if (this.trdTyp == null) {
            if (other.trdTyp != null)
                return false;
        }
        else if (!this.trdTyp.equals(other.trdTyp))
            return false;
        if (this.asSeq == null) {
            if (other.asSeq != null)
                return false;
        }
        else if (!this.asSeq.equals(other.asSeq))
            return false;
        if (this.ctgSeq == null) {
            if (other.ctgSeq != null)
                return false;
        }
        else if (!this.ctgSeq.equals(other.ctgSeq))
            return false;
        if (this.trdImgPath == null) {
            if (other.trdImgPath != null)
                return false;
        }
        else if (!this.trdImgPath.equals(other.trdImgPath))
            return false;
        if (this.creDt == null) {
            if (other.creDt != null)
                return false;
        }
        else if (!this.creDt.equals(other.creDt))
            return false;
        if (this.updDt == null) {
            if (other.updDt != null)
                return false;
        }
        else if (!this.updDt.equals(other.updDt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.trdSeq == null) ? 0 : this.trdSeq.hashCode());
        result = prime * result + ((this.mbSeq == null) ? 0 : this.mbSeq.hashCode());
        result = prime * result + ((this.trdCtt == null) ? 0 : this.trdCtt.hashCode());
        result = prime * result + ((this.trdPrc == null) ? 0 : this.trdPrc.hashCode());
        result = prime * result + ((this.trdDt == null) ? 0 : this.trdDt.hashCode());
        result = prime * result + ((this.trdTyp == null) ? 0 : this.trdTyp.hashCode());
        result = prime * result + ((this.asSeq == null) ? 0 : this.asSeq.hashCode());
        result = prime * result + ((this.ctgSeq == null) ? 0 : this.ctgSeq.hashCode());
        result = prime * result + ((this.trdImgPath == null) ? 0 : this.trdImgPath.hashCode());
        result = prime * result + ((this.creDt == null) ? 0 : this.creDt.hashCode());
        result = prime * result + ((this.updDt == null) ? 0 : this.updDt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Trade (");

        sb.append(trdSeq);
        sb.append(", ").append(mbSeq);
        sb.append(", ").append(trdCtt);
        sb.append(", ").append(trdPrc);
        sb.append(", ").append(trdDt);
        sb.append(", ").append(trdTyp);
        sb.append(", ").append(asSeq);
        sb.append(", ").append(ctgSeq);
        sb.append(", ").append(trdImgPath);
        sb.append(", ").append(creDt);
        sb.append(", ").append(updDt);

        sb.append(")");
        return sb.toString();
    }
}
