/*
 * This file is generated by jOOQ.
 */
package sun.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 이체 내역 테이블
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Transfer implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long trfSeq;
    private final Long mbSeq;
    private final String trfCtt;
    private final Long trfPrc;
    private final LocalDateTime trfDt;
    private final Long wthdrAsSeq;
    private final Long dpstAsSeq;
    private final LocalDateTime creDt;
    private final LocalDateTime updDt;

    public Transfer(Transfer value) {
        this.trfSeq = value.trfSeq;
        this.mbSeq = value.mbSeq;
        this.trfCtt = value.trfCtt;
        this.trfPrc = value.trfPrc;
        this.trfDt = value.trfDt;
        this.wthdrAsSeq = value.wthdrAsSeq;
        this.dpstAsSeq = value.dpstAsSeq;
        this.creDt = value.creDt;
        this.updDt = value.updDt;
    }

    public Transfer(
        Long trfSeq,
        Long mbSeq,
        String trfCtt,
        Long trfPrc,
        LocalDateTime trfDt,
        Long wthdrAsSeq,
        Long dpstAsSeq,
        LocalDateTime creDt,
        LocalDateTime updDt
    ) {
        this.trfSeq = trfSeq;
        this.mbSeq = mbSeq;
        this.trfCtt = trfCtt;
        this.trfPrc = trfPrc;
        this.trfDt = trfDt;
        this.wthdrAsSeq = wthdrAsSeq;
        this.dpstAsSeq = dpstAsSeq;
        this.creDt = creDt;
        this.updDt = updDt;
    }

    /**
     * Getter for <code>fintrack.TRANSFER.TRF_SEQ</code>. 이체 내역 일련번호
     */
    public Long getTrfSeq() {
        return this.trfSeq;
    }

    /**
     * Getter for <code>fintrack.TRANSFER.MB_SEQ</code>. 회원 일련번호
     */
    public Long getMbSeq() {
        return this.mbSeq;
    }

    /**
     * Getter for <code>fintrack.TRANSFER.TRF_CTT</code>. 이체 내용
     */
    public String getTrfCtt() {
        return this.trfCtt;
    }

    /**
     * Getter for <code>fintrack.TRANSFER.TRF_PRC</code>. 이체 금액
     */
    public Long getTrfPrc() {
        return this.trfPrc;
    }

    /**
     * Getter for <code>fintrack.TRANSFER.TRF_DT</code>. 이체일시
     */
    public LocalDateTime getTrfDt() {
        return this.trfDt;
    }

    /**
     * Getter for <code>fintrack.TRANSFER.WTHDR_AS_SEQ</code>. 출금 자산 일련번호
     */
    public Long getWthdrAsSeq() {
        return this.wthdrAsSeq;
    }

    /**
     * Getter for <code>fintrack.TRANSFER.DPST_AS_SEQ</code>. 입금 자산 일련번호
     */
    public Long getDpstAsSeq() {
        return this.dpstAsSeq;
    }

    /**
     * Getter for <code>fintrack.TRANSFER.CRE_DT</code>. 등록일시
     */
    public LocalDateTime getCreDt() {
        return this.creDt;
    }

    /**
     * Getter for <code>fintrack.TRANSFER.UPD_DT</code>. 수정일시
     */
    public LocalDateTime getUpdDt() {
        return this.updDt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Transfer other = (Transfer) obj;
        if (this.trfSeq == null) {
            if (other.trfSeq != null)
                return false;
        }
        else if (!this.trfSeq.equals(other.trfSeq))
            return false;
        if (this.mbSeq == null) {
            if (other.mbSeq != null)
                return false;
        }
        else if (!this.mbSeq.equals(other.mbSeq))
            return false;
        if (this.trfCtt == null) {
            if (other.trfCtt != null)
                return false;
        }
        else if (!this.trfCtt.equals(other.trfCtt))
            return false;
        if (this.trfPrc == null) {
            if (other.trfPrc != null)
                return false;
        }
        else if (!this.trfPrc.equals(other.trfPrc))
            return false;
        if (this.trfDt == null) {
            if (other.trfDt != null)
                return false;
        }
        else if (!this.trfDt.equals(other.trfDt))
            return false;
        if (this.wthdrAsSeq == null) {
            if (other.wthdrAsSeq != null)
                return false;
        }
        else if (!this.wthdrAsSeq.equals(other.wthdrAsSeq))
            return false;
        if (this.dpstAsSeq == null) {
            if (other.dpstAsSeq != null)
                return false;
        }
        else if (!this.dpstAsSeq.equals(other.dpstAsSeq))
            return false;
        if (this.creDt == null) {
            if (other.creDt != null)
                return false;
        }
        else if (!this.creDt.equals(other.creDt))
            return false;
        if (this.updDt == null) {
            if (other.updDt != null)
                return false;
        }
        else if (!this.updDt.equals(other.updDt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.trfSeq == null) ? 0 : this.trfSeq.hashCode());
        result = prime * result + ((this.mbSeq == null) ? 0 : this.mbSeq.hashCode());
        result = prime * result + ((this.trfCtt == null) ? 0 : this.trfCtt.hashCode());
        result = prime * result + ((this.trfPrc == null) ? 0 : this.trfPrc.hashCode());
        result = prime * result + ((this.trfDt == null) ? 0 : this.trfDt.hashCode());
        result = prime * result + ((this.wthdrAsSeq == null) ? 0 : this.wthdrAsSeq.hashCode());
        result = prime * result + ((this.dpstAsSeq == null) ? 0 : this.dpstAsSeq.hashCode());
        result = prime * result + ((this.creDt == null) ? 0 : this.creDt.hashCode());
        result = prime * result + ((this.updDt == null) ? 0 : this.updDt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Transfer (");

        sb.append(trfSeq);
        sb.append(", ").append(mbSeq);
        sb.append(", ").append(trfCtt);
        sb.append(", ").append(trfPrc);
        sb.append(", ").append(trfDt);
        sb.append(", ").append(wthdrAsSeq);
        sb.append(", ").append(dpstAsSeq);
        sb.append(", ").append(creDt);
        sb.append(", ").append(updDt);

        sb.append(")");
        return sb.toString();
    }
}
