/*
 * This file is generated by jOOQ.
 */
package sun.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import sun.tables.Asset;


/**
 * 자산 테이블
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AssetRecord extends UpdatableRecordImpl<AssetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>fintrack.ASSET.AS_SEQ</code>. 자산 일련번호
     */
    public AssetRecord setAsSeq(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.ASSET.AS_SEQ</code>. 자산 일련번호
     */
    public Long getAsSeq() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>fintrack.ASSET.AS_NM</code>. 자산명
     */
    public AssetRecord setAsNm(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.ASSET.AS_NM</code>. 자산명
     */
    public String getAsNm() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fintrack.ASSET.AS_AMT</code>. 자산 금액
     */
    public AssetRecord setAsAmt(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.ASSET.AS_AMT</code>. 자산 금액
     */
    public Long getAsAmt() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>fintrack.ASSET.MB_SEQ</code>. 회원 일련번호
     */
    public AssetRecord setMbSeq(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.ASSET.MB_SEQ</code>. 회원 일련번호
     */
    public Long getMbSeq() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>fintrack.ASSET.CRE_DT</code>. 등록일시
     */
    public AssetRecord setCreDt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.ASSET.CRE_DT</code>. 등록일시
     */
    public LocalDateTime getCreDt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>fintrack.ASSET.UPD_DT</code>. 수정일시
     */
    public AssetRecord setUpdDt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.ASSET.UPD_DT</code>. 수정일시
     */
    public LocalDateTime getUpdDt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AssetRecord
     */
    public AssetRecord() {
        super(Asset.ASSET);
    }

    /**
     * Create a detached, initialised AssetRecord
     */
    public AssetRecord(Long asSeq, String asNm, Long asAmt, Long mbSeq, LocalDateTime creDt, LocalDateTime updDt) {
        super(Asset.ASSET);

        setAsSeq(asSeq);
        setAsNm(asNm);
        setAsAmt(asAmt);
        setMbSeq(mbSeq);
        setCreDt(creDt);
        setUpdDt(updDt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AssetRecord
     */
    public AssetRecord(sun.tables.pojos.Asset value) {
        super(Asset.ASSET);

        if (value != null) {
            setAsSeq(value.getAsSeq());
            setAsNm(value.getAsNm());
            setAsAmt(value.getAsAmt());
            setMbSeq(value.getMbSeq());
            setCreDt(value.getCreDt());
            setUpdDt(value.getUpdDt());
            resetChangedOnNotNull();
        }
    }
}
