/*
 * This file is generated by jOOQ.
 */
package sun.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import sun.tables.Income;


/**
 * 수입 테이블
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IncomeRecord extends UpdatableRecordImpl<IncomeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>fintrack.INCOME.IC_SEQ</code>. 수입 일련번호
     */
    public IncomeRecord setIcSeq(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.INCOME.IC_SEQ</code>. 수입 일련번호
     */
    public Long getIcSeq() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>fintrack.INCOME.MB_SEQ</code>. 회원 일련번호
     */
    public IncomeRecord setMbSeq(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.INCOME.MB_SEQ</code>. 회원 일련번호
     */
    public Long getMbSeq() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>fintrack.INCOME.IC_CTT</code>. 수입 내용
     */
    public IncomeRecord setIcCtt(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.INCOME.IC_CTT</code>. 수입 내용
     */
    public String getIcCtt() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fintrack.INCOME.IC_PRC</code>. 수입 금액
     */
    public IncomeRecord setIcPrc(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.INCOME.IC_PRC</code>. 수입 금액
     */
    public Long getIcPrc() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>fintrack.INCOME.IC_DT</code>. 수입일시
     */
    public IncomeRecord setIcDt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.INCOME.IC_DT</code>. 수입일시
     */
    public LocalDateTime getIcDt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>fintrack.INCOME.AS_SEQ</code>. 자산 일련번호
     */
    public IncomeRecord setAsSeq(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.INCOME.AS_SEQ</code>. 자산 일련번호
     */
    public Long getAsSeq() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>fintrack.INCOME.CTG_ID</code>. 카테고리 아이디
     */
    public IncomeRecord setCtgId(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.INCOME.CTG_ID</code>. 카테고리 아이디
     */
    public Long getCtgId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>fintrack.INCOME.CRE_DT</code>. 등록일시
     */
    public IncomeRecord setCreDt(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.INCOME.CRE_DT</code>. 등록일시
     */
    public LocalDateTime getCreDt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>fintrack.INCOME.UPD_DT</code>. 수정일시
     */
    public IncomeRecord setUpdDt(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.INCOME.UPD_DT</code>. 수정일시
     */
    public LocalDateTime getUpdDt() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IncomeRecord
     */
    public IncomeRecord() {
        super(Income.INCOME);
    }

    /**
     * Create a detached, initialised IncomeRecord
     */
    public IncomeRecord(Long icSeq, Long mbSeq, String icCtt, Long icPrc, LocalDateTime icDt, Long asSeq, Long ctgId, LocalDateTime creDt, LocalDateTime updDt) {
        super(Income.INCOME);

        setIcSeq(icSeq);
        setMbSeq(mbSeq);
        setIcCtt(icCtt);
        setIcPrc(icPrc);
        setIcDt(icDt);
        setAsSeq(asSeq);
        setCtgId(ctgId);
        setCreDt(creDt);
        setUpdDt(updDt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised IncomeRecord
     */
    public IncomeRecord(sun.tables.pojos.Income value) {
        super(Income.INCOME);

        if (value != null) {
            setIcSeq(value.getIcSeq());
            setMbSeq(value.getMbSeq());
            setIcCtt(value.getIcCtt());
            setIcPrc(value.getIcPrc());
            setIcDt(value.getIcDt());
            setAsSeq(value.getAsSeq());
            setCtgId(value.getCtgId());
            setCreDt(value.getCreDt());
            setUpdDt(value.getUpdDt());
            resetChangedOnNotNull();
        }
    }
}
