/*
 * This file is generated by jOOQ.
 */
package sun.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import sun.tables.Member;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MemberRecord extends UpdatableRecordImpl<MemberRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>fintrack.MEMBER.MB_SEQ</code>. 회원 일련번호
     */
    public MemberRecord setMbSeq(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.MEMBER.MB_SEQ</code>. 회원 일련번호
     */
    public Long getMbSeq() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>fintrack.MEMBER.MB_EMAIL</code>. 이메일
     */
    public MemberRecord setMbEmail(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.MEMBER.MB_EMAIL</code>. 이메일
     */
    public String getMbEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fintrack.MEMBER.MB_NM</code>. 닉네임
     */
    public MemberRecord setMbNm(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.MEMBER.MB_NM</code>. 닉네임
     */
    public String getMbNm() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fintrack.MEMBER.MB_ROLE</code>. 권한
     */
    public MemberRecord setMbRole(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.MEMBER.MB_ROLE</code>. 권한
     */
    public String getMbRole() {
        return (String) get(3);
    }

    /**
     * Setter for <code>fintrack.MEMBER.MB_VALID</code>. 유효여부
     */
    public MemberRecord setMbValid(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.MEMBER.MB_VALID</code>. 유효여부
     */
    public String getMbValid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>fintrack.MEMBER.CRE_DT</code>. 등록일시
     */
    public MemberRecord setCreDt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.MEMBER.CRE_DT</code>. 등록일시
     */
    public LocalDateTime getCreDt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>fintrack.MEMBER.UPD_DT</code>. 수정일시
     */
    public MemberRecord setUpdDt(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.MEMBER.UPD_DT</code>. 수정일시
     */
    public LocalDateTime getUpdDt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MemberRecord
     */
    public MemberRecord() {
        super(Member.MEMBER);
    }

    /**
     * Create a detached, initialised MemberRecord
     */
    public MemberRecord(Long mbSeq, String mbEmail, String mbNm, String mbRole, String mbValid, LocalDateTime creDt, LocalDateTime updDt) {
        super(Member.MEMBER);

        setMbSeq(mbSeq);
        setMbEmail(mbEmail);
        setMbNm(mbNm);
        setMbRole(mbRole);
        setMbValid(mbValid);
        setCreDt(creDt);
        setUpdDt(updDt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised MemberRecord
     */
    public MemberRecord(sun.tables.pojos.Member value) {
        super(Member.MEMBER);

        if (value != null) {
            setMbSeq(value.getMbSeq());
            setMbEmail(value.getMbEmail());
            setMbNm(value.getMbNm());
            setMbRole(value.getMbRole());
            setMbValid(value.getMbValid());
            setCreDt(value.getCreDt());
            setUpdDt(value.getUpdDt());
            resetChangedOnNotNull();
        }
    }
}
