/*
 * This file is generated by jOOQ.
 */
package sun.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import sun.tables.Member;


/**
 * 회원 테이블
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MemberRecord extends UpdatableRecordImpl<MemberRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sun.member.cre_dt</code>. 생성일시
     */
    public MemberRecord setCreDt(LocalDateTime value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sun.member.cre_dt</code>. 생성일시
     */
    public LocalDateTime getCreDt() {
        return (LocalDateTime) get(0);
    }

    /**
     * Setter for <code>sun.member.mb_seq</code>. 회원 일련번호
     */
    public MemberRecord setMbSeq(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>sun.member.mb_seq</code>. 회원 일련번호
     */
    public Long getMbSeq() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>sun.member.upd_dt</code>. 수정일시
     */
    public MemberRecord setUpdDt(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>sun.member.upd_dt</code>. 수정일시
     */
    public LocalDateTime getUpdDt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>sun.member.mb_email</code>. 이메일
     */
    public MemberRecord setMbEmail(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>sun.member.mb_email</code>. 이메일
     */
    public String getMbEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sun.member.mb_valid</code>. 유효여부
     */
    public MemberRecord setMbValid(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>sun.member.mb_valid</code>. 유효여부
     */
    public String getMbValid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sun.member.mb_nm</code>. 닉네임
     */
    public MemberRecord setMbNm(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>sun.member.mb_nm</code>. 닉네임
     */
    public String getMbNm() {
        return (String) get(5);
    }

    /**
     * Setter for <code>sun.member.mb_role</code>. 권한
     */
    public MemberRecord setMbRole(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>sun.member.mb_role</code>. 권한
     */
    public String getMbRole() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MemberRecord
     */
    public MemberRecord() {
        super(Member.MEMBER);
    }

    /**
     * Create a detached, initialised MemberRecord
     */
    public MemberRecord(LocalDateTime creDt, Long mbSeq, LocalDateTime updDt, String mbEmail, String mbValid, String mbNm, String mbRole) {
        super(Member.MEMBER);

        setCreDt(creDt);
        setMbSeq(mbSeq);
        setUpdDt(updDt);
        setMbEmail(mbEmail);
        setMbValid(mbValid);
        setMbNm(mbNm);
        setMbRole(mbRole);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised MemberRecord
     */
    public MemberRecord(sun.tables.pojos.Member value) {
        super(Member.MEMBER);

        if (value != null) {
            setCreDt(value.getCreDt());
            setMbSeq(value.getMbSeq());
            setUpdDt(value.getUpdDt());
            setMbEmail(value.getMbEmail());
            setMbValid(value.getMbValid());
            setMbNm(value.getMbNm());
            setMbRole(value.getMbRole());
            resetChangedOnNotNull();
        }
    }
}
