/*
 * This file is generated by jOOQ.
 */
package sun.tables.records;


import java.time.LocalDateTime;

import org.jooq.impl.TableRecordImpl;

import sun.tables.Payment;


/**
 * 결제 테이블
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PaymentRecord extends TableRecordImpl<PaymentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sun.payment.pm_seq</code>. 결제 일련번호
     */
    public PaymentRecord setPmSeq(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sun.payment.pm_seq</code>. 결제 일련번호
     */
    public Long getPmSeq() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>sun.payment.pm_ctt</code>. 결제 내용
     */
    public PaymentRecord setPmCtt(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>sun.payment.pm_ctt</code>. 결제 내용
     */
    public String getPmCtt() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sun.payment.pm_prc</code>. 결제 금액
     */
    public PaymentRecord setPmPrc(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>sun.payment.pm_prc</code>. 결제 금액
     */
    public Long getPmPrc() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>sun.payment.mb_seq</code>. 회원 일련변호
     */
    public PaymentRecord setMbSeq(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>sun.payment.mb_seq</code>. 회원 일련변호
     */
    public Long getMbSeq() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>sun.payment.cre_dt</code>. 생성일시
     */
    public PaymentRecord setCreDt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>sun.payment.cre_dt</code>. 생성일시
     */
    public LocalDateTime getCreDt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>sun.payment.pm_ctg_id</code>. 카테고리 아이디
     */
    public PaymentRecord setPmCtgId(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>sun.payment.pm_ctg_id</code>. 카테고리 아이디
     */
    public Long getPmCtgId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PaymentRecord
     */
    public PaymentRecord() {
        super(Payment.PAYMENT);
    }

    /**
     * Create a detached, initialised PaymentRecord
     */
    public PaymentRecord(Long pmSeq, String pmCtt, Long pmPrc, Long mbSeq, LocalDateTime creDt, Long pmCtgId) {
        super(Payment.PAYMENT);

        setPmSeq(pmSeq);
        setPmCtt(pmCtt);
        setPmPrc(pmPrc);
        setMbSeq(mbSeq);
        setCreDt(creDt);
        setPmCtgId(pmCtgId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PaymentRecord
     */
    public PaymentRecord(sun.tables.pojos.Payment value) {
        super(Payment.PAYMENT);

        if (value != null) {
            setPmSeq(value.getPmSeq());
            setPmCtt(value.getPmCtt());
            setPmPrc(value.getPmPrc());
            setMbSeq(value.getMbSeq());
            setCreDt(value.getCreDt());
            setPmCtgId(value.getPmCtgId());
            resetChangedOnNotNull();
        }
    }
}
