/*
 * This file is generated by jOOQ.
 */
package sun.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import sun.tables.Trade;


/**
 * 거래 내역 테이블
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TradeRecord extends UpdatableRecordImpl<TradeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>fintrack.TRADE.TRD_SEQ</code>. 거래 일련번호
     */
    public TradeRecord setTrdSeq(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.TRADE.TRD_SEQ</code>. 거래 일련번호
     */
    public Long getTrdSeq() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>fintrack.TRADE.MB_SEQ</code>. 회원 일련번호
     */
    public TradeRecord setMbSeq(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.TRADE.MB_SEQ</code>. 회원 일련번호
     */
    public Long getMbSeq() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>fintrack.TRADE.TRD_CTT</code>. 거래 내용
     */
    public TradeRecord setTrdCtt(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.TRADE.TRD_CTT</code>. 거래 내용
     */
    public String getTrdCtt() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fintrack.TRADE.TRD_PRC</code>. 거래 금액
     */
    public TradeRecord setTrdPrc(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.TRADE.TRD_PRC</code>. 거래 금액
     */
    public Long getTrdPrc() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>fintrack.TRADE.TRD_DT</code>. 거래일시
     */
    public TradeRecord setTrdDt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.TRADE.TRD_DT</code>. 거래일시
     */
    public LocalDateTime getTrdDt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>fintrack.TRADE.TRD_TYP</code>. 거래 타입
     */
    public TradeRecord setTrdTyp(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.TRADE.TRD_TYP</code>. 거래 타입
     */
    public String getTrdTyp() {
        return (String) get(5);
    }

    /**
     * Setter for <code>fintrack.TRADE.AS_SEQ</code>. 자산 일련번호
     */
    public TradeRecord setAsSeq(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.TRADE.AS_SEQ</code>. 자산 일련번호
     */
    public Long getAsSeq() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>fintrack.TRADE.CTG_SEQ</code>. 카테고리 일련번호
     */
    public TradeRecord setCtgSeq(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.TRADE.CTG_SEQ</code>. 카테고리 일련번호
     */
    public Long getCtgSeq() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>fintrack.TRADE.TRD_IMG_PATH</code>. 이미지 경로
     */
    public TradeRecord setTrdImgPath(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.TRADE.TRD_IMG_PATH</code>. 이미지 경로
     */
    public String getTrdImgPath() {
        return (String) get(8);
    }

    /**
     * Setter for <code>fintrack.TRADE.CRE_DT</code>. 등록일시
     */
    public TradeRecord setCreDt(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.TRADE.CRE_DT</code>. 등록일시
     */
    public LocalDateTime getCreDt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>fintrack.TRADE.UPD_DT</code>. 수정일시
     */
    public TradeRecord setUpdDt(LocalDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.TRADE.UPD_DT</code>. 수정일시
     */
    public LocalDateTime getUpdDt() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TradeRecord
     */
    public TradeRecord() {
        super(Trade.TRADE);
    }

    /**
     * Create a detached, initialised TradeRecord
     */
    public TradeRecord(Long trdSeq, Long mbSeq, String trdCtt, Long trdPrc, LocalDateTime trdDt, String trdTyp, Long asSeq, Long ctgSeq, String trdImgPath, LocalDateTime creDt, LocalDateTime updDt) {
        super(Trade.TRADE);

        setTrdSeq(trdSeq);
        setMbSeq(mbSeq);
        setTrdCtt(trdCtt);
        setTrdPrc(trdPrc);
        setTrdDt(trdDt);
        setTrdTyp(trdTyp);
        setAsSeq(asSeq);
        setCtgSeq(ctgSeq);
        setTrdImgPath(trdImgPath);
        setCreDt(creDt);
        setUpdDt(updDt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TradeRecord
     */
    public TradeRecord(sun.tables.pojos.Trade value) {
        super(Trade.TRADE);

        if (value != null) {
            setTrdSeq(value.getTrdSeq());
            setMbSeq(value.getMbSeq());
            setTrdCtt(value.getTrdCtt());
            setTrdPrc(value.getTrdPrc());
            setTrdDt(value.getTrdDt());
            setTrdTyp(value.getTrdTyp());
            setAsSeq(value.getAsSeq());
            setCtgSeq(value.getCtgSeq());
            setTrdImgPath(value.getTrdImgPath());
            setCreDt(value.getCreDt());
            setUpdDt(value.getUpdDt());
            resetChangedOnNotNull();
        }
    }
}
