/*
 * This file is generated by jOOQ.
 */
package sun.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import sun.tables.Transfer;


/**
 * 이체 내역 테이블
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TransferRecord extends UpdatableRecordImpl<TransferRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>fintrack.TRANSFER.TRF_SEQ</code>. 이체 내역 일련번호
     */
    public TransferRecord setTrfSeq(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.TRANSFER.TRF_SEQ</code>. 이체 내역 일련번호
     */
    public Long getTrfSeq() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>fintrack.TRANSFER.MB_SEQ</code>. 회원 일련번호
     */
    public TransferRecord setMbSeq(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.TRANSFER.MB_SEQ</code>. 회원 일련번호
     */
    public Long getMbSeq() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>fintrack.TRANSFER.TRF_CTT</code>. 이체 내용
     */
    public TransferRecord setTrfCtt(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.TRANSFER.TRF_CTT</code>. 이체 내용
     */
    public String getTrfCtt() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fintrack.TRANSFER.TRF_PRC</code>. 이체 금액
     */
    public TransferRecord setTrfPrc(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.TRANSFER.TRF_PRC</code>. 이체 금액
     */
    public Long getTrfPrc() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>fintrack.TRANSFER.TRF_DT</code>. 이체일시
     */
    public TransferRecord setTrfDt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.TRANSFER.TRF_DT</code>. 이체일시
     */
    public LocalDateTime getTrfDt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>fintrack.TRANSFER.WTHDR_AS_SEQ</code>. 출금 자산 일련번호
     */
    public TransferRecord setWthdrAsSeq(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.TRANSFER.WTHDR_AS_SEQ</code>. 출금 자산 일련번호
     */
    public Long getWthdrAsSeq() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>fintrack.TRANSFER.DPST_AS_SEQ</code>. 입금 자산 일련번호
     */
    public TransferRecord setDpstAsSeq(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.TRANSFER.DPST_AS_SEQ</code>. 입금 자산 일련번호
     */
    public Long getDpstAsSeq() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>fintrack.TRANSFER.CRE_DT</code>. 등록일시
     */
    public TransferRecord setCreDt(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.TRANSFER.CRE_DT</code>. 등록일시
     */
    public LocalDateTime getCreDt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>fintrack.TRANSFER.UPD_DT</code>. 수정일시
     */
    public TransferRecord setUpdDt(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>fintrack.TRANSFER.UPD_DT</code>. 수정일시
     */
    public LocalDateTime getUpdDt() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransferRecord
     */
    public TransferRecord() {
        super(Transfer.TRANSFER);
    }

    /**
     * Create a detached, initialised TransferRecord
     */
    public TransferRecord(Long trfSeq, Long mbSeq, String trfCtt, Long trfPrc, LocalDateTime trfDt, Long wthdrAsSeq, Long dpstAsSeq, LocalDateTime creDt, LocalDateTime updDt) {
        super(Transfer.TRANSFER);

        setTrfSeq(trfSeq);
        setMbSeq(mbSeq);
        setTrfCtt(trfCtt);
        setTrfPrc(trfPrc);
        setTrfDt(trfDt);
        setWthdrAsSeq(wthdrAsSeq);
        setDpstAsSeq(dpstAsSeq);
        setCreDt(creDt);
        setUpdDt(updDt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TransferRecord
     */
    public TransferRecord(sun.tables.pojos.Transfer value) {
        super(Transfer.TRANSFER);

        if (value != null) {
            setTrfSeq(value.getTrfSeq());
            setMbSeq(value.getMbSeq());
            setTrfCtt(value.getTrfCtt());
            setTrfPrc(value.getTrfPrc());
            setTrfDt(value.getTrfDt());
            setWthdrAsSeq(value.getWthdrAsSeq());
            setDpstAsSeq(value.getDpstAsSeq());
            setCreDt(value.getCreDt());
            setUpdDt(value.getUpdDt());
            resetChangedOnNotNull();
        }
    }
}
