/*
 * This file is generated by jOOQ.
 */
package sun.tables;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import sun.Fintrack;
import sun.Keys;
import sun.tables.records.PaymentRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Payment extends TableImpl<PaymentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>fintrack.PAYMENT</code>
     */
    public static final Payment PAYMENT = new Payment();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PaymentRecord> getRecordType() {
        return PaymentRecord.class;
    }

    /**
     * The column <code>fintrack.PAYMENT.PM_SEQ</code>. 결제 일련번호
     */
    public final TableField<PaymentRecord, Long> PM_SEQ = createField(DSL.name("PM_SEQ"), SQLDataType.BIGINT.nullable(false).identity(true), this, "결제 일련번호");

    /**
     * The column <code>fintrack.PAYMENT.MB_SEQ</code>. 회원 일련번호
     */
    public final TableField<PaymentRecord, Long> MB_SEQ = createField(DSL.name("MB_SEQ"), SQLDataType.BIGINT.nullable(false), this, "회원 일련번호");

    /**
     * The column <code>fintrack.PAYMENT.PM_CTT</code>. 결제 내용
     */
    public final TableField<PaymentRecord, String> PM_CTT = createField(DSL.name("PM_CTT"), SQLDataType.VARCHAR(255).nullable(false), this, "결제 내용");

    /**
     * The column <code>fintrack.PAYMENT.PM_PRC</code>. 결제 금액
     */
    public final TableField<PaymentRecord, Long> PM_PRC = createField(DSL.name("PM_PRC"), SQLDataType.BIGINT.nullable(false), this, "결제 금액");

    /**
     * The column <code>fintrack.PAYMENT.PM_DT</code>. 결제일시
     */
    public final TableField<PaymentRecord, LocalDateTime> PM_DT = createField(DSL.name("PM_DT"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "결제일시");

    /**
     * The column <code>fintrack.PAYMENT.AS_SEQ</code>. 자산 일련번호
     */
    public final TableField<PaymentRecord, Long> AS_SEQ = createField(DSL.name("AS_SEQ"), SQLDataType.BIGINT.nullable(false), this, "자산 일련번호");

    /**
     * The column <code>fintrack.PAYMENT.CTG_SEQ</code>. 카테고리 일련번호
     */
    public final TableField<PaymentRecord, Long> CTG_SEQ = createField(DSL.name("CTG_SEQ"), SQLDataType.BIGINT.nullable(false), this, "카테고리 일련번호");

    /**
     * The column <code>fintrack.PAYMENT.PM_IMG_PATH</code>. 이미지 경로
     */
    public final TableField<PaymentRecord, String> PM_IMG_PATH = createField(DSL.name("PM_IMG_PATH"), SQLDataType.VARCHAR(255), this, "이미지 경로");

    /**
     * The column <code>fintrack.PAYMENT.CRE_DT</code>. 등록일시
     */
    public final TableField<PaymentRecord, LocalDateTime> CRE_DT = createField(DSL.name("CRE_DT"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "등록일시");

    /**
     * The column <code>fintrack.PAYMENT.UPD_DT</code>. 수정일시
     */
    public final TableField<PaymentRecord, LocalDateTime> UPD_DT = createField(DSL.name("UPD_DT"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "수정일시");

    private Payment(Name alias, Table<PaymentRecord> aliased) {
        this(alias, aliased, null);
    }

    private Payment(Name alias, Table<PaymentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>fintrack.PAYMENT</code> table reference
     */
    public Payment(String alias) {
        this(DSL.name(alias), PAYMENT);
    }

    /**
     * Create an aliased <code>fintrack.PAYMENT</code> table reference
     */
    public Payment(Name alias) {
        this(alias, PAYMENT);
    }

    /**
     * Create a <code>fintrack.PAYMENT</code> table reference
     */
    public Payment() {
        this(DSL.name("PAYMENT"), null);
    }

    public <O extends Record> Payment(Table<O> child, ForeignKey<O, PaymentRecord> key) {
        super(child, key, PAYMENT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Fintrack.FINTRACK;
    }

    @Override
    public Identity<PaymentRecord, Long> getIdentity() {
        return (Identity<PaymentRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PaymentRecord> getPrimaryKey() {
        return Keys.KEY_PAYMENT_PRIMARY;
    }

    @Override
    public Payment as(String alias) {
        return new Payment(DSL.name(alias), this);
    }

    @Override
    public Payment as(Name alias) {
        return new Payment(alias, this);
    }

    @Override
    public Payment as(Table<?> alias) {
        return new Payment(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Payment rename(String name) {
        return new Payment(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Payment rename(Name name) {
        return new Payment(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Payment rename(Table<?> name) {
        return new Payment(name.getQualifiedName(), null);
    }
}
