/*
 * This file is generated by jOOQ.
 */
package sun.tables;


import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import sun.Sun;
import sun.tables.records.PaymentCategoryRecord;


/**
 * 결제 카테고리 테이블
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PaymentCategory extends TableImpl<PaymentCategoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sun.payment_category</code>
     */
    public static final PaymentCategory PAYMENT_CATEGORY = new PaymentCategory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PaymentCategoryRecord> getRecordType() {
        return PaymentCategoryRecord.class;
    }

    /**
     * The column <code>sun.payment_category.pm_ctg_id</code>. 결제 카테고리 아이디
     */
    public final TableField<PaymentCategoryRecord, Long> PM_CTG_ID = createField(DSL.name("pm_ctg_id"), SQLDataType.BIGINT.nullable(false), this, "결제 카테고리 아이디");

    /**
     * The column <code>sun.payment_category.pm_ctg_nm</code>. 카테고리명
     */
    public final TableField<PaymentCategoryRecord, String> PM_CTG_NM = createField(DSL.name("pm_ctg_nm"), SQLDataType.VARCHAR(30).nullable(false), this, "카테고리명");

    private PaymentCategory(Name alias, Table<PaymentCategoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private PaymentCategory(Name alias, Table<PaymentCategoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("결제 카테고리 테이블"), TableOptions.table());
    }

    /**
     * Create an aliased <code>sun.payment_category</code> table reference
     */
    public PaymentCategory(String alias) {
        this(DSL.name(alias), PAYMENT_CATEGORY);
    }

    /**
     * Create an aliased <code>sun.payment_category</code> table reference
     */
    public PaymentCategory(Name alias) {
        this(alias, PAYMENT_CATEGORY);
    }

    /**
     * Create a <code>sun.payment_category</code> table reference
     */
    public PaymentCategory() {
        this(DSL.name("payment_category"), null);
    }

    public <O extends Record> PaymentCategory(Table<O> child, ForeignKey<O, PaymentCategoryRecord> key) {
        super(child, key, PAYMENT_CATEGORY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sun.SUN;
    }

    @Override
    public PaymentCategory as(String alias) {
        return new PaymentCategory(DSL.name(alias), this);
    }

    @Override
    public PaymentCategory as(Name alias) {
        return new PaymentCategory(alias, this);
    }

    @Override
    public PaymentCategory as(Table<?> alias) {
        return new PaymentCategory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PaymentCategory rename(String name) {
        return new PaymentCategory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PaymentCategory rename(Name name) {
        return new PaymentCategory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PaymentCategory rename(Table<?> name) {
        return new PaymentCategory(name.getQualifiedName(), null);
    }
}
